services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./credentials:/app/credentials
      - ./models:/app/models
    command: uvicorn src.ws_server:app --host 0.0.0.0 --port 8000 --reload